name: Waka Readme

on:
  schedule:
    - cron: '* */2 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
              # Show the list of OS Worked on In dev metrics
          SHOW_OS: False
          # Show the list of projects worked on in dev metrics
          SHOW_PROJECTS: False
          # Show the Editors used in dev metrics
          SHOW_EDITORS: False
          # Show the time zone in the dev metrics
          SHOW_TIMEZONE: False
          # Shows the number of commit graph in the dev metrics
          SHOW_COMMIT: False
          # Show the Coding language used in dev metrics
          SHOW_LANGUAGE: True
          # Show the Total Lines of code written Badge till date
          SHOW_LINES_OF_CODE: False
          # Show language or framework used across different repository
          SHOW_LANGUAGE_PER_REPO: False
          # 
          SHOW_LOC_CHART: False
          # show day of week you are most productive
          SHOW_DAYS_OF_WEEK: False
          # Shows the current profile views
          SHOW_PROFILE_VIEWS: False
          # Shows the short facts
          SHOW_SHORT_INFO: False
          # Show stats in your own language
          SHOW_UPDATED_DATE: False
          SHOW_TOTAL_CODE_TIME: False
          LOCALE: en
